#!/usr/bin/env perl

BEGIN {
    $ENV{UR_DBI_NO_COMMIT}=1;
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS}=1;
}

use strict;
use warnings;
use Test::More skip_all => 'broken in dist branch';

plan tests => 6;

use File::Temp;

use above 'Cord';
use Cord::Simple;

$ENV{WF_TESTDIR} = File::Temp::tempdir('CordXXXXX', DIR => '/gsc/var/cache/testsuite/running_testsuites', CLEANUP => 1);

$Cord::Simple::store_db = 0;

my $op = Cord::Operation->create(
    name => 'ls',
    operation_type => Cord::OperationType::Command->get('Cord::Test::Command::Ls')
);

my $output = run_workflow_lsf(
    $op,
);

ok(defined $output,'defined');
ok(-e $ENV{WF_TESTDIR} . '/stdout', 'stdout exists');
ok(-e $ENV{WF_TESTDIR} . '/stderr', 'stderr exists');

$op->operation_type->lsf_resource(' ' . $op->operation_type->lsf_resource);

$output = run_workflow_lsf(
    $op,
);

ok(defined $output,'w/ space defined');
ok(-e $ENV{WF_TESTDIR} . '/stdout', 'w/ space stdout exists');
ok(-e $ENV{WF_TESTDIR} . '/stderr', 'w/ space stderr exists');


