#!/usr/bin/env perl

BEGIN {
    $ENV{UR_DBI_NO_COMMIT}=1;
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS}=1;
}

use strict;
use warnings;

use Test::More tests => 4;

use above 'Workflow';

require_ok('Workflow');
require_ok('Workflow::Dispatcher');
require_ok('Workflow::Dispatcher::Lsf');

my $resource = Workflow::Resource->create(mem_limit => 100);
my $lsf = Workflow::Dispatcher::Lsf->create(cluster => "default");
my $job = Workflow::Dispatcher::Job->create(
    resource => $resource,
    command => 'echo "Hello world"'
);

my $job_id = $lsf->execute($job);
print $job_id . "\n";
ok($job_id, "Job id exists");
